# Generated by Django 5.0.4 on 2024-05-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='cataory',
            new_name='catagory',
        ),
    ]
