# Generated by Django 5.0.4 on 2024-05-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_cataory_menuitem_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catagory',
        ),
    ]
